### ISSUE TITLE
DNS123是不是没法访问谷歌了？

### ISSUE THREAD

**Issue by wuchichou** [SUSTech-CRA/sustech-online-ng#110]
在创园十栋把路由器DNS改成DNS123，但还是没法访问谷歌和谷歌学术。

**Comment by liziwl** [comment]
@sparkcyf please help to check

**Comment by sparkcyf** [comment]
> 在创园十栋把路由器DNS改成DNS123，但还是没法访问谷歌和谷歌学术。

您好，请在想关电脑上提供一下 curl -v https://scholar.google.com 的结果以便我们进行调查。

**Comment by wuchichou** [comment]
> > 在创园十栋把路由器DNS改成DNS123，但还是没法访问谷歌和谷歌学术。
> 
> 您好，请在相关电脑上提供一下 curl -v https://scholar.google.com 的结果以便我们进行调查。

下午的时候还不行，现在试了一下，又可以了。关闭issue。
