### ISSUE TITLE
最近更新功能

### ISSUE THREAD

**Issue by xiaoheyh** [SUSTech-CRA/sustech-online-ng#130]
主页上增加一个关于近期更新的动态页面，类似于wiki

**Comment by liziwl** [comment]
之前考虑的是首页上更新比较占用版面，后来就开了个快讯站 https://daily.sustech.online/ 。但是有时候更新懒了就没更新快讯站 😂。

小程序上有专门的tab进去，移动网页端也可以点击这里 
![image](https://user-images.githubusercontent.com/23000702/204814773-28b8fa67-559f-40e6-95c0-f4f3e5641403.png)
