### ISSUE TITLE
想好奇一波公交的实时GPS是怎么获取的

### ISSUE THREAD

**Issue by JalinWang** [SUSTech-CRA/sustech-online-ng#136]
校园交通中心提供呢，还是说类似高德这种公共平台？

**Comment by liziwl** [comment]
> 校园交通中心提供呢，还是说类似高德这种公共平台？

和校服办合作提供的。

**Comment by JalinWang** [comment]
公交车上自带的GPS和姿态系统上报给内网服务器？

**Comment by liziwl** [comment]
学校招标的校园交通服务，含有有一个巴士运行状态的网页控制台，也有API。手册定期去轮询的公网API，查询巴士状态。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by liziwl** [comment]
那个接口只有基础GPS和姿态数据，手册上的可视化还有时间路线预测都是手册自己做的。
