### ISSUE TITLE
搜索插件转跳不准确问题

### ISSUE THREAD

**Issue by chenyuheng** [SUSTech-CRA/sustech-online-ng#16]
附件为演示问题的视频：
[screenrecord.zip](https://github.com/SUSTC/sustech-online-ng/files/5560073/screenrecord.zip)

**Comment by liziwl** [comment]
插件问题：https://github.com/leo-buneev/vuepress-plugin-fulltext-search

表格导致的索引错误

**Comment by liziwl** [comment]
https://github.com/meilisearch/vuepress-plugin-meilisearch

感觉可以试一试上面的解决方案

**Comment by liziwl** [comment]
@chenyuheng @sparkcyf 我部署了meilisearch 在 http://test.liziwl.cn/，你们觉得这个搜索结果咋样。

> https://github.com/meilisearch/vuepress-plugin-meilisearch
> 
> 感觉可以试一试上面的解决方案

**Comment by sparkcyf** [comment]
感觉效果比之前那个好一些，我最近找个时间部署在国内的轻量服务器吧 。

**Comment by liziwl** [comment]
需要适配暗黑模式

**Comment by sparkcyf** [comment]
搜索系统已经更换为了algolia，此问题暂时关闭。
